-- AItiopia migration v2 — status workflow, integrity constraints, RLS
-- Run in Supabase SQL editor (Dashboard → SQL Editor → New query).
--
-- ⚠ ONE-SHOT: the backfill in section 3 marks all existing rows as
--   published. Do not re-run this file after drafts exist.
--
-- Context: the live DB never received migrate-schema.sql — the series
-- table does not exist and images has only the original 10 columns.
-- This file supersedes migrate-schema.sql: it creates everything that
-- one added, plus the status workflow, constraints, and RLS.

-- ─── 1. series table (does not exist yet) ────────────────────────────────────

CREATE TABLE IF NOT EXISTS series (
  slug             TEXT PRIMARY KEY,
  title            TEXT NOT NULL,
  description      TEXT NOT NULL DEFAULT '',
  sort_order       INTEGER NOT NULL DEFAULT 0,
  long_description TEXT,
  og_image_path    TEXT,
  keywords         TEXT[],
  color_accent     TEXT
);

INSERT INTO series (slug, title, description, sort_order, long_description, keywords, color_accent)
VALUES
  ('letters',       'Letters',       'Individual Ethiopic Fidel characters visualised through AI.',      1,
   'A series exploring individual characters of the Ethiopic script (Fidel). Each image renders a single letter as a visual artwork generated by AI, celebrating the 2,500-year-old writing system of Ethiopia.',
   ARRAY['Ethiopian letters', 'Fidel', 'Ethiopic script', 'Ge-ez', 'AI art', 'Amharic letters'],
   '#7B5CF0'),
  ('words',         'Words',         'Amharic words and phrases brought to life with AI imagery.',       2,
   'A series where Amharic words and phrases become visual artworks. Each image pairs the written word with an AI-generated visual interpretation, bridging language and image.',
   ARRAY['Amharic words', 'Ethiopian language', 'Ge-ez', 'AI art', 'Amharic typography'],
   '#D946A8'),
  ('miscellaneous', 'Miscellaneous', 'Experimental and mixed works from the AItiopia project.',          3,
   'Experimental works that do not fit neatly into Letters or Words — abstract explorations, mixed forms, and boundary-pushing AI imagery rooted in Ethiopian visual culture.',
   ARRAY['Ethiopian AI art', 'experimental art', 'Ethiopic', 'AI image generation'],
   '#06B6D4'),
  ('year',          'Year',          'Annual retrospectives and time-based collections.',                4,
   'Annual collections marking milestones in the AItiopia project — a time-stamped archive of how Ethiopian script and AI artistry have evolved together.',
   ARRAY['Ethiopian art archive', 'AI art collection', 'Ethiopic script', 'annual'],
   '#F59E0B')
ON CONFLICT (slug) DO NOTHING;

-- ─── 2. images: new columns ──────────────────────────────────────────────────

ALTER TABLE images
  ADD COLUMN IF NOT EXISTS title            TEXT,
  ADD COLUMN IF NOT EXISTS alt_text         TEXT,
  ADD COLUMN IF NOT EXISTS description      TEXT,
  ADD COLUMN IF NOT EXISTS ge_ez_character  TEXT,
  ADD COLUMN IF NOT EXISTS transliteration  TEXT,
  ADD COLUMN IF NOT EXISTS featured         BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS blur_data_url    TEXT,
  -- status workflow: processing → draft → published → rejected
  -- New rows default to draft; the ingest Edge Function sets processing/draft explicitly.
  ADD COLUMN IF NOT EXISTS status           TEXT NOT NULL DEFAULT 'draft',
  -- AI vision pre-fill suggestions, stored at ingest time for the curate page
  ADD COLUMN IF NOT EXISTS ai_suggestions   JSONB,
  -- sha256 of file bytes — catches duplicate uploads regardless of filename
  ADD COLUMN IF NOT EXISTS content_hash     TEXT,
  ADD COLUMN IF NOT EXISTS updated_at       TIMESTAMPTZ NOT NULL DEFAULT now();

-- ─── 3. Backfill (ONE-SHOT — everything currently in the DB is live) ─────────

UPDATE images SET status = 'published' WHERE status = 'draft';

-- ─── 4. Integrity constraints ────────────────────────────────────────────────

ALTER TABLE images DROP CONSTRAINT IF EXISTS images_status_check;
ALTER TABLE images ADD CONSTRAINT images_status_check
  CHECK (status IN ('processing', 'draft', 'published', 'rejected'));

ALTER TABLE images DROP CONSTRAINT IF EXISTS images_storage_path_key;
ALTER TABLE images ADD CONSTRAINT images_storage_path_key UNIQUE (storage_path);

ALTER TABLE images DROP CONSTRAINT IF EXISTS images_series_fkey;
ALTER TABLE images ADD CONSTRAINT images_series_fkey
  FOREIGN KEY (series) REFERENCES series(slug);

-- ─── 5. updated_at trigger ───────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS images_updated_at ON images;
CREATE TRIGGER images_updated_at
  BEFORE UPDATE ON images
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─── 6. Indexes ──────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_images_status       ON images (status);
CREATE INDEX IF NOT EXISTS idx_images_series       ON images (series);
CREATE INDEX IF NOT EXISTS idx_images_featured     ON images (featured) WHERE featured;
CREATE INDEX IF NOT EXISTS idx_images_content_hash ON images (content_hash);

-- ─── 7. Row Level Security ───────────────────────────────────────────────────
-- The site reads with the anon key; scripts and the Edge Function use the
-- service role key, which bypasses RLS. Anon must only ever see published rows.

ALTER TABLE images ENABLE ROW LEVEL SECURITY;
ALTER TABLE series ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon reads published images" ON images;
CREATE POLICY "anon reads published images"
  ON images FOR SELECT
  TO anon
  USING (status = 'published');

DROP POLICY IF EXISTS "anyone reads series" ON series;
CREATE POLICY "anyone reads series"
  ON series FOR SELECT
  USING (true);

-- ─── Verification (run after — all should return expected values) ────────────
-- SELECT count(*) FROM series;                                   -- 4
-- SELECT status, count(*) FROM images GROUP BY status;           -- published: 64
-- SELECT relrowsecurity FROM pg_class WHERE relname = 'images';  -- t
