-- AItiopia schema migration
-- Run this in your Supabase SQL editor (Dashboard → SQL Editor → New query)

-- ─── images table: add new columns ──────────────────────────────────────────

ALTER TABLE images
  ADD COLUMN IF NOT EXISTS title            TEXT,
  ADD COLUMN IF NOT EXISTS alt_text         TEXT,
  ADD COLUMN IF NOT EXISTS description      TEXT,
  ADD COLUMN IF NOT EXISTS ge_ez_character  TEXT,
  ADD COLUMN IF NOT EXISTS transliteration  TEXT,
  ADD COLUMN IF NOT EXISTS published        BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS featured         BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS blur_data_url    TEXT;

-- ─── series table: add new columns ──────────────────────────────────────────

ALTER TABLE series
  ADD COLUMN IF NOT EXISTS long_description TEXT,
  ADD COLUMN IF NOT EXISTS og_image_path    TEXT,
  ADD COLUMN IF NOT EXISTS keywords         TEXT[],
  ADD COLUMN IF NOT EXISTS color_accent     TEXT;

-- ─── Seed series rows (run once if series table is empty) ───────────────────
-- Adjust sort_order and descriptions to match your existing data.

INSERT INTO series (slug, title, description, sort_order, long_description, keywords, color_accent)
VALUES
  ('letters',       'Letters',       'Individual Ethiopic Fidel characters visualised through AI.',      1,
   'A series exploring individual characters of the Ethiopic script (Fidel). Each image renders a single letter as a visual artwork generated by AI, celebrating the 2,500-year-old writing system of Ethiopia.',
   ARRAY['Ethiopian letters', 'Fidel', 'Ethiopic script', 'Ge-ez', 'AI art', 'Amharic letters'],
   '#7B5CF0'),

  ('words',         'Words',         'Amharic words and phrases brought to life with AI imagery.',       2,
   'A series where Amharic words and phrases become visual artworks. Each image pairs the written word with an AI-generated visual interpretation, bridging language and image.',
   ARRAY['Amharic words', 'Ethiopian language', 'Ge-ez', 'AI art', 'Amharic typography'],
   '#D946A8'),

  ('miscellaneous', 'Miscellaneous', 'Experimental and mixed works from the AItiopia project.',          3,
   'Experimental works that do not fit neatly into Letters or Words — abstract explorations, mixed forms, and boundary-pushing AI imagery rooted in Ethiopian visual culture.',
   ARRAY['Ethiopian AI art', 'experimental art', 'Ethiopic', 'AI image generation'],
   '#06B6D4'),

  ('year',          'Year',          'Annual retrospectives and time-based collections.',                4,
   'Annual collections marking milestones in the AItiopia project — a time-stamped archive of how Ethiopian script and AI artistry have evolved together.',
   ARRAY['Ethiopian art archive', 'AI art collection', 'Ethiopic script', 'annual'],
   '#F59E0B')

ON CONFLICT (slug) DO NOTHING;

-- ─── Helpful index for published + featured queries ──────────────────────────

CREATE INDEX IF NOT EXISTS idx_images_published   ON images (published);
CREATE INDEX IF NOT EXISTS idx_images_featured    ON images (featured);
CREATE INDEX IF NOT EXISTS idx_images_series      ON images (series);
